# -*- coding: utf-8 -*-
"""Fase3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V3JS4axOUtVOolID-WVgkppe9GSrxSfz

Crie um algoritmo em Python que peça uma nota, entre zero e 100. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

# INSIRA SEU CÓDIGO AQUI
while True:
  try:
    nota = float(input("Insira uma nota entre 0 a 100:"))
    if 0 <= nota <= 100:
      print(f"Você inseriu o número {nota}")
      break
    else:
      print("O número que digitou está fora do range.")
  except:
    print("Você inseriu uma letra/palavra, tente novamente.")

"""Crie um algoritmo em Python que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.<br>"""

# INSIRA SEU CÓDIGO AQUI
import PySimpleGUI as sg

sg.theme('BluePurple')   # Tema da tela
# Layout da tela, os botoes e os campos para digitação
layout = [  [sg.Text('Usuário'), sg.Input()],
            [sg.Text('Senha'), sg.Input()],
            [sg.Button('Entrar'), sg.Button('Cancel')] ]

layout_2 = [    [sg.Text("Você inseriu usuário e senha iguais, tente novamente")],
                [sg.Button("OK")] ]

# Criando janela
window = sg.Window('Validação de usuário', layout)
window_2 = sg.Window("Erro", layout_2)
# Como foi inserido dois inputs, será criada um dicionário nomeado como values e a variável event receberá o nome dos campos.
while True:
    event, values = window.read()
    if event in (None, 'Cancel'):   # Para fechar a janela clicar em cancel.
        break
    if values[1] == values[0]:
        event2, values2 = window_2.read() # Abrindo janela 2 se as senhas e usuário forem iguais
    window_2.close() #Clicando em ok a janela é fechada
window.close()

"""Crie um algoritmo em Python que leia e valide as seguintes informações:
* Nome: maior que 3 caracteres;
* Idade: entre 0 e 150;
* Salário: maior que zero;
* Sexo: 'f' ou 'm';
* Estado Civil: 's', 'c', 'v', 'd';
"""

# INSIRA SEU CÓDIGO AQUI
import PySimpleGUI as sg

sg.theme('BluePurple')   # Tema da tela
# Layout da tela, os botoes e os campos para digitação
layout_tela1 = [ [sg.Text("Nome"), sg.Input(key="nome")],
                 [sg.Text("Idade"), sg.Input(key= "idade")],
                 [sg.Text("Salário"), sg.Input(key = "salario")],
                 [sg.Text("Sexo")],
                 [sg.Radio("Masculino", "sexo",key = "masculino"), sg.Radio("Feminino","sexo", key = "feminino")],
                 [sg.Text("Estado Civil")],
                 [sg.Checkbox("Solteiro", key = "solteiro"),sg.Checkbox("Casado", key = "casado"),sg.Checkbox("Viuvo(a)",key = "v"),sg.Checkbox("Divorciado", key = "divorcio")],
                 [sg.Button("Submeter"),sg.Button("Cancel")]
                 ]

layout_tela2 = [[sg.Text("Houve um erro, coloque as informações certas.")],
               [sg.Button("Ok")],
               ]

layout_tela3 = [[sg.Text("Informações Salvas com sucesso!")]]

janela1 = sg.Window("Validação").layout(layout_tela1)
janela2 = sg.Window("Erro", layout=layout_tela2)
janela3 = sg.Window("Fim do programa").layout(layout_tela3)

while True:
    try:
        texto, entradas = janela1.read()
        print(layout_tela1)
        print(layout_tela2)
        if texto in (None,"Cancel"):
            break
        else:
            if float(entradas["idade"]) == str or float(entradas["salario"]) == str or entradas["nome"] == float:
                janela2.read()
                janela2.close()
            else:
                janela3.read()
                janela3.close()
                break
    except ValueError:
        janela2.read()
        janela2.close()

janela1.close()

"""Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%.<br><br> Crie um algoritmo em Python que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento."""

# INSIRA SEU CÓDIGO AQUI

"""Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer número inteiro entre 1 a 10. O usuário deve informar de qual numero ele deseja ver a tabuada. A saída deve ser conforme o exemplo abaixo:
Tabuada de 5:<br>
5 X 1 = 5<br>
5 X 2 = 10<br>
...<br>
5 X 10 = 50<br>
"""

# INSIRA SEU CÓDIGO AQUI

"""Crie um algoritmo em Python que leia três números e mostre o maior e o menor deles."""

# INSIRA SEU CÓDIGO AQUI
try:
  i = 0
  lista = []
  while i <= 2:
    num = float(input("Escreva um número:"))
    lista.append(num)
    i = i + 1

  lista_nova = sorted(lista)
  print(f"O menor elemento é {lista_nova[0]}, e o maior elemento é o {lista_nova[len(lista_nova)-1]}")
except ValueError:
  print("Algo deu errado, tente novamente")

"""Crie um algoritmo em Python que peça 2 números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem."""

# INSIRA SEU CÓDIGO AQUI
base = float(input("Insira a base: "))
exp = float(input("Insira o expoente: "))
print(f"O primeiro numero elevado ao segundo é {base**exp}")

"""Crie um algoritmo em Python que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares."""

# INSIRA SEU CÓDIGO AQUI
try:
  i = 0
  pares = 0
  impares = 0
  lista = []
  while i < 10:
    num = float(input("Insira um valor: "))
    lista.append(num)
  for j in lista:
    if j%2 == 0:
      pares += 1
    else:
      impares += 1
  print(f"Tem {pares} números pares e {impares} numero impares")
except ValueError:
  print("Algo deu errado, tente novamente!")

"""Um funcionário de uma empresa recebe aumento salarial anualmente: Sabe-se que:
Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00;
Em 1996 recebeu aumento de 1,5% sobre seu salário inicial;
A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Crie um algoritmo em Python que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário.
"""

# INSIRA SEU CÓDIGO AQUI

"""Crie um algoritmo em Python com uma função que necessite de um argumento. A função retorna o valor de caractere ‘P’, se seu argumento for positivo, e ‘N’, se seu argumento for zero ou negativo."""

# INSIRA SEU CÓDIGO AQUI

"""Construa uma função que receba uma data no formato DD/MM/AAAA e devolva uma string no formato D de mesPorExtenso de AAAA. Opcionalmente, valide a data e retorne NULL caso a data seja inválida."""

# INSIRA SEU CÓDIGO AQUI

"""Crie uma classe que modele uma pessoa:<br>

Atributos: nome, idade, peso e altura<br>
Métodos: Envelhercer, engordar, emagrecer, crescer.<br>
<br>Obs: Por padrão, a cada ano que nossa pessoa envelhece, sendo a idade dela menor que 21 anos, ela deve crescer 0,5 cm.
"""

# INSIRA SEU CÓDIGO AQUI
help(classmethod)